### ISSUE TITLE
Types don't work in a SvelteKit project

### ISSUE THREAD

**Issue by cshaa** [bechii/svelte-create-context#1]
If I add the package to a SvelteKit app, trying to import it like so:
```ts
import { createContext } from 'svelte-create-context';
```
throws "Module '"svelte-create-context"' has no exported member 'createContext'." If I ctrl+click on the package name, I get to `node_modules/svelte-create-context/dist/types/main.d.ts`, which looks like this:
```ts
export * from './createContext';
```
If I change it to the following, it starts working again:
```ts
export * from './createContext.d.ts';
```

**Comment by bechii** [comment]
Hi
I'm currently using it myself in a SvelteKit project without any problems. What version of typescript are you using ?

**Comment by cshaa** [comment]
Hey!
Thanks for getting back to me! I tried to create a new SvelteKit project, and you are right, it _does_ work. The problem in my old SvelteKit project was having `"moduleResolution": "nodenext"` in my `tsconfig.json`. After setting module resolution to `"bundler"`, the package works as expected.
